### ISSUE TITLE
have a bug 

### ISSUE THREAD

**Issue by xxdoc** [OlimilO1402/Win_Dialogs#2]
Private Type BrowseInfo
    hwndOwner      As Long
    pidlRoot       As Long
    **pszDisplayName As Long 'String
    lpszTitle      As Long 'String**
    ulFlags        As Long
    lpfn           As Long
    lParam         As Long
    iImage         As Long
End Type

======================================
 With BI
        .hwndOwner = hhwndOwner
        .pidlRoot = pRoot
        '.pszDisplayName = ""
        'Beschreibung im Dialog 'als nullterminierter String
        **.lpszTitle = mDescription '& vbNullChar  ========================='may be bug .**
        .ulFlags = mFlags
        .lpfn = FncPtr(AddressOf MCallBack.FolderBrowserDialogCallBack)
        .lParam = ObjPtr(Me)
        .iImage = 0&
    End With

**Comment by xxdoc** [comment]
if selesc  SpecialFolder_Desktop then click the foldbrowser button.the exe crashed

**Comment by xxdoc** [comment]
i test in win10 homesysetem

**Comment by OlimilO1402** [comment]
hi xxdoc, thank you very much for creating the issue ticket, every communication in github is highly appreciated 👍 
Oh there is so much to say . . . 
1. at the beginning of the 2022, trying to run FolderBrowser in win_dialgs.exe crashed also on my windows. 
And now it still does not run but it does *not* crash, instead it says "type mismatch" (winver: 21H2 19044.1889)
2. Please have a look at the microsoft article about SHBrowseForFolder function: https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shbrowseforfolderw see Remarks it says it is better to use OpenFolderDialog of course you can find it here
3. However I will try to fix FolderBrowserDialog asap just because I like it ;-)

**Comment by OlimilO1402** [comment]
fixed
